- job:
    name: gerrit-buck
    parent: legacy-base
    pre-run: playbooks/gerrit-buck/pre.yaml
    run: playbooks/gerrit-buck/run.yaml
    post-run: playbooks/gerrit-buck/post.yaml
    vars:
      buck_publish_path: 'test'
    timeout: 2400

- job:
    name: gerrit-package-buck
    parent: publish-openstack-artifacts
    pre-run: playbooks/gerrit-buck/pre.yaml
    run: playbooks/gerrit-buck/run.yaml
    post-run: playbooks/gerrit-buck/post.yaml
    vars:
      buck_publish_path: 'gerrit'
    timeout: 2400

- job:
    name: its-storyboard-gerrit-plugin-stable-2.13
    parent: publish-openstack-artifacts
    run: playbooks/its-storyboard-gerrit-plugin-stable-2.13/run.yaml
    post-run: playbooks/its-storyboard-gerrit-plugin-stable-2.13/post.yaml
    timeout: 1800

- job:
    name: javamelody-gerrit-plugin-stable-2.13
    parent: publish-openstack-artifacts
    run: playbooks/javamelody-gerrit-plugin-stable-2.13/run.yaml
    post-run: playbooks/javamelody-gerrit-plugin-stable-2.13/post.yaml
    timeout: 1800

- project:
    check:
      jobs:
        - gerrit-buck
    gate:
      jobs:
        - gerrit-buck
    post:
      jobs:
        - gerrit-package-buck
    periodic:
      jobs:
        - javamelody-gerrit-plugin-stable-2.13
        - its-storyboard-gerrit-plugin-stable-2.13
