- hosts: all
  tasks:
    - name: Copy gerrit files from {{ ansible_user_dir }} to logs
      synchronize:
        src: '{{ ansible_user_dir }}/workspace/'
        dest: '{{ zuul.executor.log_root }}/gerrit'
        mode: pull
        copy_links: true
        rsync_opts:
          - --include=/gerrit/buck-out/gen/gerrit-*.war
          - --include=*/
          - --exclude=*
          - --prune-empty-dirs
