- hosts: all
  name: Autoconverted job legacy-gerrit-buck from old job gate-gerrit-buck
  roles:
    # for version-properties.sh
    - legacy-copy-jenkins-scripts
    - bindep
    - revoke-sudo

  tasks:
    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          set -e
          set -x
          if [[ ! -d "buck" ]]
          then
            git clone https://gerrit.googlesource.com/buck
            cd buck
            ant
          fi
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          CLONEMAP=`mktemp`
          function cleanup {
              rm -f $CLONEMAP
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: openstack-infra/gerrit
              dest: gerrit
          EOF
          /usr/zuul-env/bin/zuul-cloner -m $CLONEMAP \
              --cache-dir /opt/git \
              git://git.openstack.org openstack-infra/gerrit
          cd gerrit
          # This is necessary to build the core plugins
          git submodule init
          git submodule update
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          set -e
          set -x
          export PATH=`pwd`/buck/bin:$PATH
          cd gerrit
          /usr/local/jenkins/slave_scripts/version-properties.sh
          source version.properties
          buck clean
          buck test --all --exclude slow
          buck build release
          cp buck-out/gen/release/release.war buck-out/gen/gerrit-$PROJECT_VER.war
        executable: /bin/bash
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
